"""Secure Cloudinary integration for the Venus API.

This module is backend-only. The Cloudinary API secret must never be shipped
in a web/mobile application. Production clients receive only short-lived
signed upload parameters generated by this backend.
"""
from __future__ import annotations

import os
import re
import time
import uuid
from pathlib import Path
from typing import Any

import cloudinary
import cloudinary.uploader
from cloudinary.utils import api_sign_request, verify_api_response_signature
from dotenv import load_dotenv

ROOT = Path(__file__).resolve().parent
load_dotenv(ROOT / ".env")

_SAFE_ID = re.compile(r"^[A-Za-z0-9_-]+$")


def _required(name: str) -> str:
    value = os.getenv(name, "").strip()
    if not value:
        raise RuntimeError(f"Variável obrigatória ausente: {name}")
    return value


def _int_env(name: str, default: int) -> int:
    try:
        value = int(os.getenv(name, str(default)))
    except ValueError as exc:
        raise RuntimeError(f"{name} deve ser inteiro") from exc
    if value <= 0:
        raise RuntimeError(f"{name} deve ser maior que zero")
    return value


def configure() -> None:
    """Configure the official Cloudinary SDK from backend-only environment variables."""
    cloudinary.config(
        cloud_name=_required("CLOUDINARY_CLOUD_NAME"),
        api_key=_required("CLOUDINARY_API_KEY"),
        api_secret=_required("CLOUDINARY_API_SECRET"),
        secure=True,
        signature_algorithm=os.getenv("CLOUDINARY_SIGNATURE_ALGORITHM", "sha256"),
    )


def _safe_id(value: int | str) -> str:
    text = str(value).strip()
    if not _SAFE_ID.fullmatch(text):
        raise ValueError("Identificador inválido para Cloudinary public_id")
    return text


def _allowed_formats() -> list[str]:
    formats = [x.strip().lower() for x in os.getenv("CLOUDINARY_ALLOWED_FORMATS", "jpg,jpeg,png,webp").split(",")]
    result = [x for x in formats if x]
    if not result:
        raise RuntimeError("CLOUDINARY_ALLOWED_FORMATS não pode ser vazio")
    return result


def _folder_root() -> str:
    root = os.getenv("CLOUDINARY_IMAGE_FOLDER", "venus").strip("/")
    if not root or "." in root or ".." in root:
        raise RuntimeError("CLOUDINARY_IMAGE_FOLDER inválido")
    return root


def avatar_public_id(user_id: int) -> str:
    return f"{_folder_root()}/users/{_safe_id(user_id)}/avatar"


def product_photo_public_id(product_version_id: int, token: str | None = None) -> str:
    suffix = token or uuid.uuid4().hex
    return f"{_folder_root()}/products/{_safe_id(product_version_id)}/photos/{_safe_id(suffix)}"


def _signed_preset() -> str | None:
    value = os.getenv("CLOUDINARY_SIGNED_UPLOAD_PRESET", "").strip()
    return value or None


def generate_signed_upload_params(
    *,
    purpose: str,
    owner_id: int,
    overwrite: bool = False,
) -> dict[str, Any]:
    """Generate the exact short-lived parameters a client can send to Cloudinary.

    The server decides the public_id/folder and signs every mutable upload field.
    The secret itself is never returned. The PostgreSQL canonical media record
    lives in venus.media_assets; this service does not mirror media metadata into
    users or product_versions.
    """
    configure()
    if purpose == "avatar":
        public_id = avatar_public_id(owner_id)
        folder = f"{_folder_root()}/users"
    elif purpose == "product_photo":
        public_id = product_photo_public_id(owner_id)
        folder = f"{_folder_root()}/products/{_safe_id(owner_id)}/photos"
        overwrite = False
    else:
        raise ValueError("purpose deve ser 'avatar' ou 'product_photo'")

    timestamp = int(time.time())
    ttl = min(_int_env("CLOUDINARY_SIGNED_UPLOAD_TTL_SECONDS", 3600), 3600)
    params_to_sign: dict[str, Any] = {
        "timestamp": timestamp,
        "folder": folder,
        "public_id": public_id,
        "overwrite": "true" if overwrite else "false",
    }
    preset = _signed_preset()
    if preset:
        params_to_sign["upload_preset"] = preset

    signature = api_sign_request(params_to_sign, _required("CLOUDINARY_API_SECRET"))

    response: dict[str, Any] = {
        "cloud_name": _required("CLOUDINARY_CLOUD_NAME"),
        "api_key": _required("CLOUDINARY_API_KEY"),
        "timestamp": timestamp,
        "signature": signature,
        "signature_algorithm": os.getenv("CLOUDINARY_SIGNATURE_ALGORITHM", "sha256"),
        "folder": folder,
        "public_id": public_id,
        "overwrite": overwrite,
        "resource_type": "image",
        "expires_in": ttl,
        "allowed_formats": _allowed_formats(),
        "max_file_size": _int_env("CLOUDINARY_UPLOAD_MAX_BYTES", 10 * 1024 * 1024),
    }
    if preset:
        response["upload_preset"] = preset
    return response


def verify_upload_response(response: dict[str, Any]) -> bool:
    """Verify the signature returned by Cloudinary before persisting metadata."""
    signature = response.get("signature")
    if not signature:
        raise ValueError("Resposta do Cloudinary sem signature")
    return bool(
        verify_api_response_signature(
            response,
            _required("CLOUDINARY_API_SECRET"),
        )
    )


def upload_from_backend(file_path: str, *, public_id: str, overwrite: bool = False) -> dict[str, Any]:
    """Optional trusted backend-to-Cloudinary upload for server-side jobs."""
    configure()
    return cloudinary.uploader.upload(
        str(Path(file_path)),
        resource_type="image",
        public_id=public_id,
        overwrite=overwrite,
        invalidate=True,
        allowed_formats=_allowed_formats(),
        max_file_size=_int_env("CLOUDINARY_UPLOAD_MAX_BYTES", 10 * 1024 * 1024),
    )


def delete_asset(public_id: str, *, resource_type: str = "image") -> dict[str, Any]:
    """Delete a Cloudinary asset. Management operations stay backend-only."""
    configure()
    return cloudinary.uploader.destroy(
        public_id,
        resource_type=resource_type,
        invalidate=True,
    )
