SET search_path TO venus, public;



INSERT INTO ingredient_categories (name, description) VALUES
    ('Não classificado', 'Categoria técnica de governança: função cosmética ainda não determinada por fonte oficial'),
    ('Emoliente', 'Reduz a perda de agua transepidérmica e melhora a maciez da pele'),
    ('Umectante', 'Atrai e retém água na pele ou no cabelo'),
    ('Oclusivo', 'Forma uma barreira física que reduz a evaporação de água'),
    ('Tensoativo', 'Reduz a tensão superficial e auxilia na limpeza'),
    ('Agente de Limpeza', 'Ajuda a remover sujeira, óleo e resíduos'),
    ('Solvente', 'Dissolve outros componentes da fórmula'),
    ('Emulsionante', 'Estabiliza a mistura entre as fases aquosa e oleosa'),
    ('Espessante', 'Aumenta a viscosidade da fórmula'),
    ('Estabilizante', 'Mantém a estabilidade físico-química da formulação'),
    ('Conservante', 'Previne contaminação e crescimento microbiológico'),
    ('Antioxidante', 'Previne a oxidação dos componentes da fórmula'),
    ('Agente Quelante', 'Complexa íons metálicos que poderiam desestabilizar a fórmula'),
    ('Agente Tampão', 'Ajuda a manter o pH da formulação'),
    ('Ajustador de pH', 'Corrige o pH da fórmula'),
    ('Formador de Filme', 'Forma uma película na superfície da pele ou do cabelo'),
    ('Condicionante', 'Proporciona condicionamento para pele ou cabelo'),
    ('Condicionante Capilar', 'Condicionamento específico do cabelo'),
    ('Condicionante da Pele', 'Condicionamento específico da pele'),
    ('Hidratante', 'Promove e mantém a hidratação da pele'),
    ('Filtro UV', 'Proporciona proteção contra radiação ultravioleta'),
    ('Absorvedor de UV', 'Filtro UV químico que absorve radiação ultravioleta'),
    ('Refletor de UV', 'Filtro UV físico/mineral que reflete radiação ultravioleta'),
    ('Fragrância', 'Adiciona odor ao produto'),
    ('Agente Perfumante', 'Usado para perfumar o produto'),
    ('Corante', 'Adiciona cor ao produto'),
    ('Agente Opacificante', 'Confere opacidade à formulação'),
    ('Agente Perolizante', 'Confere efeito perolado'),
    ('Abrasivo', 'Promove esfoliação mecânica'),
    ('Absorvente', 'Absorve óleo e umidade'),
    ('Antiestático', 'Reduz o acúmulo de eletricidade estática'),
    ('Antiespumante', 'Reduz a formação de espuma'),
    ('Agente Espumante', 'Promove a formação de espuma'),
    ('Propelente', 'Usado para dispensar produtos aerosol'),
    ('Plastificante', 'Confere flexibilidade a filmes e formulações'),
    ('Controlador de Viscosidade', 'Controla a viscosidade final da fórmula'),
    ('Aglutinante', 'Une os componentes da fórmula'),
    ('Texturizante', 'Ajusta a textura sensorial do produto'),
    ('Antiaglomerante', 'Evita a formação de grumos em produtos em pó'),
    ('Veículo', 'Transporta outros ingredientes ativos'),
    ('Ingrediente Ativo', 'Ativo cosmético com função terapêutica ou de performance declarada'),
    ('Agente Anti-inflamatório', 'Ajuda a reduzir efeitos relacionados à inflamação'),
    ('Agente Antimicrobiano', 'Ajuda a inibir o crescimento microbiano'),
    ('Agente Antifúngico', 'Ajuda a inibir o crescimento de fungos'),
    ('Agente Desodorante', 'Ajuda a controlar odores'),
    ('Regulador de Sebo', 'Ajuda a regular a produção de sebo'),
    ('Iluminador da Pele', 'Ajuda a iluminar a aparência da pele'),
    ('Fortalecedor Capilar', 'Ajuda a fortalecer as fibras capilares'),
    ('Agente Reparador Capilar', 'Ajuda a reparar fios danificados'),
    ('Definidor de Cachos', 'Realça o padrão de cachos'),
    ('Agente Suavizante', 'Ajuda a suavizar a superfície da pele ou do cabelo'),
    ('Volumizador', 'Adiciona volume aos cabelos'),
    ('Agente Antiqueda', 'Ajuda a reduzir a aparência de queda capilar'),
    ('Agente Calmante do Couro Cabeludo', 'Ajuda a acalmar o couro cabeludo'),
    ('Agente Queratolítico', 'Ajuda a remover excesso de queratina ou células mortas'),
    ('Enzima', 'Ingrediente enzimático usado para tratamento ou esfoliação'),
    ('Esfoliante', 'Remove células mortas da superfície da pele'),
    ('Agente de Dispersão', 'Ajuda a dispersar pigmentos ou sólidos'),
    ('Agente Suspensor', 'Mantém partículas suspensas na fórmula'),
    ('Solubilizante', 'Ajuda a dissolver ingredientes pouco solúveis'),
    ('Promotor de Penetração', 'Melhora a penetração de ingredientes'),
    ('Agente Encapsulante', 'Encapsula e protege ativos'),
    ('Modificador Sensorial', 'Altera a percepção sensorial do produto'),
    ('Agente Refrescante', 'Produz sensação de frescor'),
    ('Agente Aquecedor', 'Produz sensação de aquecimento'),
    ('Lubrificante', 'Melhora o deslizamento e a espalhabilidade'),
    ('Agente de Slip', 'Melhora a espalhabilidade e o toque'),
    ('Agente Anti-vermelhidão', 'Ajuda a reduzir a aparência de vermelhidão'),
    ('Agente de Suporte à Barreira', 'Suporta a barreira cutânea'),
    ('Protetor da Pele', 'Protege a superfície da pele'),
    ('Fixador', 'Ajuda a estabilizar fragrância ou fórmula'),
    ('Agente de Fixação', 'Ajuda a fixar o produto no lugar'),
    ('Adesivo', 'Melhora a adesão à pele, cabelo ou unhas'),
    ('Fortalecedor de Unhas', 'Ajuda a fortalecer unhas'),
    ('Agente Condicionante de Unhas', 'Ajuda a condicionar unhas e cutículas'),
    ('Colorante Capilar', 'Usado para colorir o cabelo'),
    ('Agente Oxidante', 'Oxida componentes durante coloração ou processamento'),
    ('Agente Redutor', 'Reduz componentes durante processamento'),
    ('Agente Descolorante', 'Ajuda a clarear pigmentos ou cabelo'),
    ('Agente Desembaraçante', 'Ajuda a reduzir nós e embaraços'),
    ('Agente Resistente à Umidade', 'Ajuda a resistir aos efeitos da umidade'),
    ('Agente Anti-frizz', 'Ajuda a controlar o frizz'),
    ('Filtro de Luz Azul', 'Ajuda a proteger contra exposição à luz azul'),
    ('Agente Anti-poluição', 'Ajuda a proteger contra os efeitos da poluição'),
    ('Agente Desodorizante', 'Ajuda a reduzir odores')
ON CONFLICT (name) DO NOTHING;

INSERT INTO product_categories (name, description) VALUES
    ('Limpador Facial', 'Produto de limpeza facial'),
    ('Bálsamo de Limpeza', 'Limpador em óleo ou bálsamo para remover maquiagem e impurezas'),
    ('Óleo de Limpeza', 'Limpador em óleo para o rosto'),
    ('Gel de Limpeza', 'Limpador em gel para o rosto'),
    ('Espuma de Limpeza', 'Limpador facial espumante'),
    ('Água Micelar', 'Água micelar de limpeza'),
    ('Tônico', 'Tônico facial'),
    ('Essência', 'Essência facial'),
    ('Sérum', 'Sérum de tratamento'),
    ('Ampola', 'Ampola de tratamento concentrado'),
    ('Hidratante', 'Hidratante facial'),
    ('Creme para Olhos', 'Creme para a região dos olhos'),
    ('Óleo Facial', 'Óleo facial'),
    ('Bruma Facial', 'Bruma facial'),
    ('Protetor Solar', 'Produto de proteção solar'),
    ('Bálsamo Labial', 'Hidratante labial'),
    ('Tratamento Local', 'Tratamento localizado para imperfeições'),
    ('Esfoliante', 'Produto esfoliante'),
    ('Máscara Facial', 'Máscara facial'),
    ('Máscara Noturna', 'Máscara noturna leave-on'),
    ('Loção Corporal', 'Loção corporal'),
    ('Manteiga Corporal', 'Manteiga corporal'),
    ('Sabonete Corporal', 'Sabonete líquido corporal'),
    ('Óleo Corporal', 'Óleo corporal'),
    ('Creme para Mãos', 'Creme para as mãos'),
    ('Creme para Pés', 'Creme para os pés'),
    ('Creme para Estrias', 'Creme para cuidado de estrias'),
    ('Creme para Celulite', 'Creme para cuidado de celulite'),
    ('Creme Firmador', 'Creme corporal firmador'),
    ('Óleo de Massagem', 'Óleo de massagem'),
    ('Higiene Íntima', 'Produto para higiene íntima'),
    ('Shampoo', 'Shampoo capilar'),
    ('Condicionador', 'Condicionador capilar'),
    ('Máscara Capilar', 'Máscara capilar'),
    ('Leave-in', 'Produto capilar leave-in'),
    ('Óleo Capilar', 'Óleo capilar'),
    ('Sérum Capilar', 'Sérum capilar'),
    ('Creme para Pentear', 'Creme para modelagem capilar'),
    ('Protetor Térmico', 'Produto capilar de proteção térmica'),
    ('Tônico Capilar', 'Tônico capilar'),
    ('Tratamento para Couro Cabeludo', 'Produto de tratamento do couro cabeludo'),
    ('Shampoo Seco', 'Shampoo seco'),
    ('Spray de Cabelo', 'Spray capilar'),
    ('Mousse Capilar', 'Mousse capilar'),
    ('Gel Capilar', 'Gel capilar'),
    ('Pomada Capilar', 'Pomada capilar'),
    ('Pasta Capilar', 'Pasta capilar'),
    ('Argila Capilar', 'Argila capilar'),
    ('Ativador de Cachos', 'Ativador de cachos'),
    ('Gel de Cachos', 'Gel para definição de cachos'),
    ('Óleo para Barba', 'Óleo para barba'),
    ('Balm para Barba', 'Balm para barba'),
    ('Shampoo para Barba', 'Shampoo para barba'),
    ('Pós-barba', 'Produto pós-barba'),
    ('Creme de Barbear', 'Creme de barbear'),
    ('Espuma de Barbear', 'Espuma de barbear'),
    ('Base', 'Base facial'),
    ('Corretivo', 'Corretivo'),
    ('Primer', 'Primer'),
    ('Pó Facial', 'Pó facial'),
    ('Blush', 'Blush'),
    ('Máscara de Cílios', 'Máscara de cílios'),
    ('Batom', 'Batom'),
    ('Esmalte', 'Esmalte'),
    ('Tratamento para Unhas', 'Tratamento para unhas'),
    ('Óleo de Cutícula', 'Óleo de cutícula'),
    ('Sabonete', 'Sabonete'),
    ('Desodorante', 'Desodorante'),
    ('Antitranspirante', 'Antitranspirante'),
    ('Enxaguante Bucal', 'Enxaguante bucal'),
    ('Creme Dental', 'Creme dental'),
    ('Creme Dental Clareador', 'Creme dental clareador'),
    ('Fio Dental', 'Fio dental'),
    ('Perfume', 'Perfume'),
    ('Água de Colônia', 'Água de colônia'),
    ('Eau de Parfum', 'Eau de parfum'),
    ('Body Splash', 'Body splash'),
    ('Shampoo Infantil', 'Shampoo infantil'),
    ('Loção Infantil', 'Loção infantil'),
    ('Óleo Infantil', 'Óleo infantil'),
    ('Creme Infantil', 'Creme infantil'),
    ('Protetor Solar Infantil', 'Protetor solar infantil'),
    ('Sabonete Infantil', 'Sabonete infantil'),
    ('Sérum Facial', 'Categoria geral de sérum facial'),
    ('Tratamento Capilar', 'Categoria geral de tratamento capilar'),
    ('Sérum para Couro Cabeludo', 'Sérum para couro cabeludo'),
    ('Removedor de Maquiagem', 'Removedor de maquiagem'),
    ('Fixador de Maquiagem', 'Spray fixador'),
    ('BB Cream', 'BB cream'),
    ('CC Cream', 'CC cream'),
    ('Base Sérum', 'Base sérum'),
    ('Hidratante com Cor', 'Hidratante com cor'),
    ('Álcool em Gel', 'Álcool em gel'),
    ('Creme Clássico', 'Creme clássico'),
    ('Pós-sol', 'Cuidado pós-sol'),
    ('Pré-shampoo', 'Tratamento pré-shampoo'),
    ('Ampola Capilar', 'Ampola capilar')
ON CONFLICT (name) DO NOTHING;

INSERT INTO score_categories (name, description, default_weight) VALUES
    ('Segurança', 'Segurança geral da formulação para o usuário', 40.0),
    ('Compatibilidade', 'Compatibilidade do produto com o perfil do usuário', 35.0),
    ('Efetividade', 'Eficácia esperada para o fim declarado', 35.0),
    ('Evidência Científica', 'Força do suporte científico para ativos e claims', 30.0),
    ('Risco Alérgico', 'Risco de reação alérgica associado à formulação', 30.0),
    ('Impacto Ambiental', 'Impacto ambiental da formulação e produção', 25.0),
    ('Sustentabilidade', 'Sustentabilidade geral do produto e da marca', 25.0),
    ('Transparência', 'Transparência das informações de ingredientes e fórmula', 20.0),
    ('Qualidade dos Ingredientes', 'Qualidade percebida dos ingredientes utilizados', 20.0),
    ('Equilíbrio da Fórmula', 'Equilíbrio técnico e coerência da formulação', 20.0),
    ('Sistema Conservante', 'Adequação do sistema conservante', 15.0),
    ('Potencial de Irritação', 'Potencial de irritação cutânea', 25.0),
    ('Risco Comedogênico', 'Risco de obstrução dos poros', 20.0),
    ('Compatibilidade com Acne', 'Adequação para pele acneica', 20.0),
    ('Pele Sensível', 'Adequação para pele sensível', 20.0),
    ('Segurança na Gravidez', 'Segurança durante gravidez e amamentação', 15.0),
    ('Cruelty Free', 'Ausência de testes em animais', 10.0),
    ('Vegano', 'Ausência de ingredientes de origem animal', 10.0),
    ('Sustentabilidade da Embalagem', 'Sustentabilidade da embalagem', 10.0),
    ('Preço vs Performance', 'Equilíbrio entre preço e performance', 10.0),
    ('Segurança de Longo Prazo', 'Perfil de segurança no uso prolongado', 20.0),
    ('Segurança de Curto Prazo', 'Perfil de segurança no uso imediato', 15.0),
    ('Integridade do Claim', 'Confiabilidade das alegações', 20.0),
    ('Sinergia de Ingredientes', 'Sinergia entre ingredientes', 15.0),
    ('Estabilidade da Fórmula', 'Estabilidade no uso/armazenamento', 15.0),
    ('Experiência Sensorial', 'Textura, toque e experiência sensorial', 10.0),
    ('Compatibilidade Capilar', 'Adequação às necessidades capilares', 20.0),
    ('Compatibilidade do Couro Cabeludo', 'Adequação às necessidades do couro cabeludo', 20.0),
    ('Qualidade do Pigmento', 'Qualidade da performance de cor/pigmento', 10.0),
    ('Risco de Fragrância', 'Risco associado à exposição à fragrância', 20.0),
    ('Robustez Microbiológica', 'Robustez contra contaminação microbiológica', 15.0),
    ('Estabilidade de Prateleira', 'Resistência à degradação ao longo do tempo', 15.0)
ON CONFLICT (name) DO NOTHING;

INSERT INTO profile_tags (name, description, slug, category) VALUES
    ('Muito Seca', 'Pele extremamente seca, com necessidade intensa de hidratação', 'muito-seca', 'skin'),
    ('Reativa', 'Pele que reage facilmente a novos produtos ou ingredientes', 'reativa', 'skin'),
    ('Pele Madura', 'Pele madura com foco em firmeza e elasticidade', 'pele-madura', 'skin'),
    ('Pele Adolescente', 'Pele adolescente com necessidades específicas', 'pele-adolescente', 'skin'),
    ('Olhos Sensíveis', 'Usuário com sensibilidade na região dos olhos', 'olhos-sensiveis', 'health'),
    ('Usuário de Lentes de Contato', 'Usuário que usa lentes de contato', 'usuario-de-lentes-de-contato', 'health'),
    ('Amamentação', 'Usuário em fase de amamentação', 'amamentacao', 'health'),
    ('Manchas Escuras', 'Presença de manchas escuras/hiperpigmentação', 'manchas-escuras', 'health'),
    ('Rugas', 'Presença de rugas', 'rugas', 'health'),
    ('Linhas Finas', 'Presença de linhas finas de expressão', 'linhas-finas', 'health'),
    ('Vermelhidão', 'Vermelhidão na pele', 'vermelhidao', 'health'),
    ('Poros Dilatados', 'Poros visivelmente dilatados', 'poros-dilatados', 'health'),
    ('Caspa', 'Presença de caspa', 'caspa', 'health'),
    ('Queda de Cabelo', 'Queda de cabelo', 'queda-de-cabelo', 'health'),
    ('Dermatite Seborreica', 'Dermatite seborreica', 'dermatite-seborreica', 'health'),
    ('Frizz', 'Frizz no cabelo', 'frizz', 'hair'),
    ('Pontas Duplas', 'Pontas duplas', 'pontas-duplas', 'hair'),
    ('Baixa Porosidade', 'Baixa porosidade capilar', 'baixa-porosidade', 'hair'),
    ('Porosidade Média', 'Porosidade média capilar', 'porosidade-media', 'hair'),
    ('Alta Porosidade', 'Alta porosidade capilar', 'alta-porosidade', 'hair'),
    ('Fios Finos', 'Fios finos', 'fios-finos', 'hair'),
    ('Fios Médios', 'Fios de espessura média', 'fios-medios', 'hair'),
    ('Fios Grossos', 'Fios grossos', 'fios-grossos', 'hair'),
    ('Quimicamente Tratado', 'Cabelo com química', 'quimicamente-tratado', 'hair'),
    ('Colorido', 'Cabelo tingido/colorido', 'colorido', 'hair'),
    ('Descolorido', 'Cabelo descolorido', 'descolorido', 'hair'),
    ('Transição Capilar', 'Cabelo em transição capilar', 'transicao-capilar', 'hair'),
    ('Vegano', 'Preferência por produtos veganos', 'vegano', 'values'),
    ('Cruelty Free', 'Preferência por produtos livres de testes em animais', 'cruelty-free', 'values'),
    ('Sem Fragrância', 'Preferência por produtos sem fragrância', 'sem-fragrancia', 'values'),
    ('Sem Álcool', 'Preferência por produtos sem álcool', 'sem-alcool', 'values'),
    ('Sem Silicone', 'Preferência por produtos sem silicone', 'sem-silicone', 'values'),
    ('Sem Parabenos', 'Preferência por produtos sem parabenos', 'sem-parabenos', 'values'),
    ('Sem Sulfato', 'Preferência por produtos sem sulfato', 'sem-sulfato', 'values'),
    ('Sem Óleos Essenciais', 'Preferência por produtos sem óleos essenciais', 'sem-oleos-essenciais', 'values'),
    ('Orgânico', 'Preferência por produtos orgânicos', 'organico', 'values'),
    ('Ingredientes Naturais', 'Preferência por ingredientes naturais', 'ingredientes-naturais', 'values'),
    ('Testado Dermatologicamente', 'Preferência por produtos testados dermatologicamente', 'testado-dermatologicamente', 'values'),
    ('Reparo da Barreira', 'Preocupação com reparo da barreira cutânea', 'reparo-da-barreira', 'skin'),
    ('Controle de Acne', 'Necessidade de controle de acne', 'controle-de-acne', 'skin'),
    ('Controle de Oleosidade', 'Necessidade de controle de oleosidade', 'controle-de-oleosidade', 'skin'),
    ('Hidratação', 'Necessidade de hidratação', 'hidratacao', 'skin'),
    ('Anti-idade', 'Necessidade de cuidado anti-idade', 'anti-idade', 'skin'),
    ('Iluminação', 'Necessidade de iluminação/viço', 'iluminacao', 'skin'),
    ('Cuidados com o Couro Cabeludo', 'Necessidade de cuidados com o couro cabeludo', 'cuidados-com-o-couro-cabeludo', 'hair'),
    ('Crescimento Capilar', 'Necessidade de apoio ao crescimento capilar', 'crescimento-capilar', 'hair'),
    ('Definição de Cachos', 'Necessidade de definição de cachos', 'definicao-de-cachos', 'hair'),
    ('Volume', 'Necessidade de volume capilar', 'volume', 'hair'),
    ('Reparação', 'Necessidade de reparação', 'reparacao', 'hair'),
    ('Usuário de Ferramentas Térmicas', 'Usa ferramentas térmicas para cabelo', 'usuario-de-ferramentas-termicas', 'hair'),
    ('Usuário Outdoor', 'Exposto ao ambiente externo com frequência', 'usuario-outdoor', 'values'),
    ('Rotina de Academia', 'Pratica exercícios regularmente', 'rotina-de-academia', 'values'),
    ('Clima Quente', 'Vive em clima quente', 'clima-quente', 'values'),
    ('Clima Frio', 'Vive em clima frio', 'clima-frio', 'values'),
    ('Clima Seco', 'Vive em clima seco', 'clima-seco', 'values'),
    ('Clima Úmido', 'Vive em clima úmido', 'clima-umido', 'values'),
    ('Pele Acneica', 'Pele acneica', 'pele-acneica', 'skin'),
    ('Melasma', 'Condição de melasma', 'melasma', 'skin'),
    ('Rosácea', 'Condição de rosácea', 'rosacea', 'skin'),
    ('Hiperpigmentação', 'Condição de hiperpigmentação', 'hiperpigmentacao', 'skin'),
    ('Eczema', 'Condição de eczema', 'eczema', 'skin'),
    ('Psoríase', 'Condição de psoríase', 'psoriase', 'skin'),
    ('Ceratose Pilar', 'Condição de ceratose pilar', 'ceratose-pilar', 'skin'),
    ('Foliculite', 'Condição de foliculite', 'foliculite', 'skin'),
    ('Seborreia', 'Condição de seborreia', 'seborreia', 'skin'),
    ('Acne Hormonal', 'Acne hormonal', 'acne-hormonal', 'skin'),
    ('Acne Adulta', 'Acne adulta', 'acne-adulta', 'skin'),
    ('Reef Safe', 'Preferência por produtos reef-safe', 'reef-safe', 'values'),
    ('Sem Microplásticos', 'Preferência por produtos sem microplásticos', 'sem-microplasticos', 'values'),
    ('Sem Óleo de Palma', 'Preferência por produtos sem óleo de palma', 'sem-oleo-de-palma', 'values'),
    ('Ingredientes Biotech', 'Preferência por ingredientes biotech', 'ingredientes-biotech', 'values'),
    ('Ingredientes Fermentados', 'Preferência por ingredientes fermentados', 'ingredientes-fermentados', 'values'),
    ('Propenso a Cravos', 'Preocupação com risco de obstrução', 'propenso-a-cravos', 'skin'),
    ('Couro Cabeludo Sensível', 'Couro cabeludo sensível', 'couro-cabeludo-sensivel', 'hair'),
    ('Couro Cabeludo Seco', 'Couro cabeludo seco', 'couro-cabeludo-seco', 'hair'),
    ('Couro Cabeludo Oleoso', 'Couro cabeludo oleoso', 'couro-cabeludo-oleoso', 'hair'),
    ('Quebra Capilar', 'Preocupação com quebra capilar', 'quebra-capilar', 'hair'),
    ('Proteção da Cor', 'Necessidade de proteger cabelos coloridos', 'protecao-da-cor', 'hair'),
    ('Brilho', 'Necessidade de brilho', 'brilho', 'hair'),
    ('Controle de Frizz', 'Necessidade de controle de frizz', 'controle-de-frizz', 'hair'),
    ('Alta Cobertura', 'Preferência por maquiagem de alta cobertura', 'alta-cobertura', 'values'),
    ('Cobertura Leve', 'Preferência por maquiagem de cobertura leve', 'cobertura-leve', 'values'),
    ('À Prova d''Água', 'Preferência por maquiagem à prova d''água', 'a-prova-dagua', 'values'),
    ('Resistente à Transferência', 'Preferência por maquiagem resistente à transferência', 'resistente-a-transferencia', 'values'),
    ('Resistente ao Suor', 'Necessidade de produtos resistentes ao suor', 'resistente-ao-suor', 'values'),
    ('Secagem Rápida', 'Necessidade de produtos de secagem rápida', 'secagem-rapida', 'values'),
    ('Lábios Sensíveis', 'Sensibilidade nos lábios', 'labios-sensiveis', 'health'),
    ('Mãos Sensíveis', 'Sensibilidade nas mãos', 'maos-sensiveis', 'health'),
    ('Pés Sensíveis', 'Sensibilidade nos pés', 'pes-sensiveis', 'health'),
    ('Cuidado Infantil', 'Público infantil', 'cuidado-infantil', 'health'),
    ('Cuidado Masculino', 'Público masculino', 'cuidado-masculino', 'values'),
    ('Rotina Luxuosa', 'Preferência por rotina premium', 'rotina-luxuosa', 'values'),
    ('Rotina Econômica', 'Preferência por rotina econômica', 'rotina-economica', 'values'),
    ('Rotina Minimalista', 'Preferência por rotina simples', 'rotina-minimalista', 'values'),
    ('Rotina Avançada', 'Preferência por rotina com múltiplas etapas', 'rotina-avancada', 'values')
ON CONFLICT (name) DO NOTHING;

INSERT INTO claims (name, description, claim_type) VALUES
    ('Hidratante', 'Confere hidratação', 'performance'),
    ('Umectante', 'Fornece efeito umectante/hidratação contínua', 'performance'),
    ('Iluminador', 'Ajuda a iluminar a aparência da pele', 'performance'),
    ('Anti-idade', 'Ajuda a reduzir sinais visíveis de envelhecimento', 'performance'),
    ('Antiacne', 'Ajuda a controlar acne', 'performance'),
    ('Controle de Oleosidade', 'Controla a oleosidade', 'performance'),
    ('Controle de Sebo', 'Ajuda a controlar a produção de sebo', 'performance'),
    ('Matificante', 'Proporciona acabamento mate', 'performance'),
    ('Calmante', 'Acalma a pele', 'performance'),
    ('Suavizante', 'Ajuda a reduzir desconforto ou irritação', 'performance'),
    ('Reparador', 'Suporta o reparo da barreira cutânea', 'performance'),
    ('Reparo da Barreira', 'Repara a barreira cutânea', 'performance'),
    ('Firmador', 'Proporciona firmeza', 'performance'),
    ('Efeito Lifting', 'Proporciona efeito lifting', 'performance'),
    ('Melhora da Elasticidade', 'Melhora a elasticidade da pele', 'performance'),
    ('Redução de Rugas', 'Reduz a aparência de rugas', 'performance'),
    ('Redução de Manchas', 'Reduz a aparência de manchas escuras', 'performance'),
    ('Anti-frizz', 'Reduz o frizz capilar', 'performance'),
    ('Definição de Cachos', 'Define cachos', 'performance'),
    ('Proteção Térmica', 'Protege o cabelo do calor', 'performance'),
    ('Proteção UV', 'Protege contra radiação UV', 'safety'),
    ('Proteção SPF', 'Possui fator de proteção solar declarado', 'safety'),
    ('Resistente à Água', 'Resistente à água', 'performance'),
    ('Resistente ao Suor', 'Resistente ao suor', 'performance'),
    ('Longa Duração', 'Efeito de longa duração', 'marketing'),
    ('Absorção Rápida', 'Absorve rapidamente', 'performance'),
    ('Secagem Rápida', 'Seca rapidamente', 'performance'),
    ('Não Comedogênico', 'Não obstrui os poros', 'safety'),
    ('Testado Dermatologicamente', 'Testado dermatologicamente', 'safety'),
    ('Hipolergênico', 'Baixo potencial alergênico', 'safety'),
    ('Sem Fragrância', 'Sem fragrância adicionada', 'safety'),
    ('Sem Álcool', 'Sem álcool na formulação', 'safety'),
    ('Sem Parabenos', 'Sem parabenos na formulação', 'safety'),
    ('Sem Silicone', 'Sem silicone na formulação', 'safety'),
    ('Sem Sulfato', 'Sem sulfato na formulação', 'safety'),
    ('Sem Óleo Mineral', 'Sem óleo mineral na formulação', 'safety'),
    ('Cruelty Free', 'Não testado em animais', 'ethical'),
    ('Vegano', 'Livre de ingredientes de origem animal', 'ethical'),
    ('Fórmula Natural', 'Fórmula predominantemente natural', 'marketing'),
    ('Ingredientes Orgânicos', 'Contém ingredientes orgânicos certificados', 'sustainability'),
    ('Fórmula Biodegradável', 'Fórmula biodegradável', 'sustainability'),
    ('Embalagem Ecológica', 'Embalagem de baixo impacto ambiental', 'sustainability'),
    ('Refilável', 'Embalagem refilável', 'sustainability'),
    ('Embalagem Reciclável', 'Embalagem reciclável', 'sustainability'),
    ('Anti-poluição', 'Ajuda a proteger contra poluição', 'performance'),
    ('Proteção Luz Azul', 'Ajuda a proteger contra luz azul', 'safety'),
    ('Suporte à Barreira', 'Suporta a barreira cutânea', 'performance'),
    ('Clarificante', 'Ajuda a clarificar pele ou cabelo', 'performance'),
    ('Limpeza Profunda', 'Proporciona limpeza profunda', 'performance'),
    ('Esfoliante', 'Proporciona esfoliação', 'performance'),
    ('Efeito Peeling', 'Proporciona efeito peeling', 'performance'),
    ('Minimizador de Poros', 'Ajuda a minimizar a aparência dos poros', 'performance'),
    ('Redução de Vermelhidão', 'Ajuda a reduzir a aparência de vermelhidão', 'performance'),
    ('Amigo da Pele Sensível', 'Adequado para pele sensível', 'safety'),
    ('Seguro na Gravidez', 'Adequado para gestação', 'safety'),
    ('Seguro na Amamentação', 'Adequado para amamentação', 'safety'),
    ('Calmante do Couro Cabeludo', 'Ajuda a acalmar o couro cabeludo', 'performance'),
    ('Controle de Caspa', 'Ajuda a controlar caspa', 'performance'),
    ('Fortalecimento Capilar', 'Ajuda a fortalecer o cabelo', 'performance'),
    ('Reparo Capilar', 'Ajuda a reparar fios danificados', 'performance'),
    ('Suporte ao Crescimento Capilar', 'Ajuda a apoiar o crescimento capilar', 'performance'),
    ('Proteção da Cor', 'Ajuda a proteger a cor do cabelo', 'performance'),
    ('Proteção UV Capilar', 'Protege o cabelo contra UV', 'performance'),
    ('Brilho', 'Impulsiona o brilho', 'marketing'),
    ('Volume', 'Impulsiona o volume do cabelo', 'performance'),
    ('Redução de Pontas Duplas', 'Ajuda a reduzir a aparência de pontas duplas', 'performance'),
    ('Antiquebra', 'Ajuda a reduzir a quebra', 'performance'),
    ('Equilíbrio Hidrolipídico', 'Suporta o equilíbrio hidrolipídico', 'performance'),
    ('Cuidado com Seborreia', 'Ajuda no cuidado de pele com seborreia', 'performance'),
    ('Amigo da Pele Acneica', 'Adequado para pele acneica', 'safety'),
    ('Amigo do Melasma', 'Adequado para pele com melasma', 'safety'),
    ('Amigo da Rosácea', 'Adequado para pele com rosácea', 'safety'),
    ('Testado para Olhos Sensíveis', 'Testado para olhos sensíveis', 'safety'),
    ('Amigo de Usuários de Lentes de Contato', 'Adequado para usuários de lentes de contato', 'safety'),
    ('Testado em Pediatria', 'Testado em pediatria', 'safety'),
    ('Controle de Odor', 'Ajuda a controlar odor', 'performance'),
    ('Sensação de Frescor', 'Proporciona sensação de frescor', 'marketing'),
    ('Não Pegajoso', 'Sensação não pegajosa', 'performance'),
    ('Não Oleoso', 'Sensação não oleosa', 'performance'),
    ('Acabamento Sedoso', 'Acabamento sedoso', 'marketing'),
    ('Acabamento Suave', 'Acabamento suave', 'marketing'),
    ('Acabamento Mate', 'Acabamento mate', 'marketing'),
    ('Acabamento Brilhante', 'Acabamento brilhante', 'marketing'),
    ('Alta Cobertura', 'Alta cobertura', 'performance'),
    ('Cobertura Construível', 'Cobertura construível', 'performance'),
    ('Cobertura Leve', 'Cobertura leve', 'performance'),
    ('Resistente à Transferência', 'Resistente à transferência', 'performance'),
    ('À Prova de Borrões', 'À prova de borrões', 'performance'),
    ('À Prova d''Água', 'À prova d''água', 'performance'),
    ('Fixação Rápida', 'Fixa rapidamente', 'performance'),
    ('Fácil de Enxaguar', 'Fácil de enxaguar', 'performance'),
    ('Hidratação Profunda', 'Hidratação profunda', 'performance'),
    ('Hidratação 24h', 'Hidratação por 24 horas', 'performance'),
    ('Hidratação 48h', 'Hidratação por 48 horas', 'performance'),
    ('Hidratação Instantânea', 'Hidratação instantânea', 'performance'),
    ('Complexo Anti-idade', 'Complexo anti-idade', 'marketing'),
    ('Cuidado com Rugas', 'Cuida das rugas', 'performance'),
    ('Complexo Firmador', 'Complexo firmador', 'marketing'),
    ('Efeito Glow', 'Entrega efeito glow', 'marketing'),
    ('Fragrância Fresca', 'Fragrância fresca', 'marketing'),
    ('Sem Scent', 'Sem aroma', 'safety'),
    ('Sem Óleos Essenciais', 'Livre de óleos essenciais', 'safety'),
    ('Sem Fragrância Adicionada', 'Sem fragrância adicionada', 'safety'),
    ('Sem Óleo de Palma', 'Livre de óleo de palma', 'sustainability'),
    ('Sem Microplásticos', 'Livre de microplásticos', 'sustainability'),
    ('Reef Safe', 'Reef safe', 'sustainability'),
    ('Carbono Neutro', 'Carbono neutro', 'sustainability'),
    ('Plástico Neutro', 'Plástico neutro', 'sustainability'),
    ('Embalagem FSC', 'Embalagem certificada FSC', 'sustainability'),
    ('Certificado RSPO', 'Certificado RSPO', 'sustainability'),
    ('Comércio Justo', 'Fornecimento de comércio justo', 'ethical'),
    ('Clinicamente Testado', 'Clinicamente testado', 'safety'),
    ('Oftalmologicamente Testado', 'Oftalmologicamente testado', 'safety'),
    ('Dermatologicamente Testado', 'Dermatologicamente testado', 'safety'),
    ('Testado para Alergia', 'Testado para alergia', 'safety'),
    ('Não Irritante', 'Não irritante', 'safety'),
    ('Baixo Resíduo', 'Baixo resíduo', 'performance'),
    ('Alto Deslizamento', 'Alto deslizamento', 'performance'),
    ('Desembaraçante', 'Ajuda a desembaraçar', 'performance'),
    ('Anti-umidade', 'Ajuda a resistir à umidade', 'performance'),
    ('Long Wear', 'Long wear', 'marketing'),
    ('Aplicação Fácil', 'Aplicação fácil', 'marketing'),
    ('Sem Bagunça', 'Aplicação sem bagunça', 'marketing'),
    ('Aprovado por Dermatologista', 'Aprovado por dermatologista', 'marketing'),
    ('Seguro para Acne', 'Adequado para pele acneica', 'safety'),
    ('Amigo da Barreira', 'Amigo da barreira cutânea', 'performance'),
    ('Suporte à Barreira Hidrolipídica', 'Suporta a barreira hidrolipídica', 'performance'),
    ('Equilíbrio de Sebo', 'Equilibra o sebo', 'performance'),
    ('Anti-vermelhidão', 'Ajuda a reduzir vermelhidão', 'performance'),
    ('Anti-coceira', 'Ajuda a reduzir coceira', 'performance'),
    ('Sensação Calmante', 'Sensação calmante', 'marketing'),
    ('Refrescante', 'Sensação refrescante', 'marketing'),
    ('Sem White Cast', 'Sem white cast', 'performance'),
    ('Com Cor', 'Fórmula com cor', 'marketing'),
    ('Acabamento Invisível', 'Acabamento invisível', 'marketing'),
    ('Ação Rápida', 'Ação rápida', 'marketing'),
    ('Dupla Ação', 'Dupla ação', 'marketing'),
    ('Tripla Ação', 'Tripla ação', 'marketing'),
    ('Complexo Reparador', 'Complexo reparador', 'marketing'),
    ('Nutritivo', 'Nutritivo', 'performance'),
    ('Condicionante', 'Condicionante', 'performance'),
    ('Protetor', 'Protetor', 'performance'),
    ('Fortalecedor', 'Fortalecedor', 'performance'),
    ('Volumizador', 'Volumizador', 'performance'),
    ('Controle de Frizz', 'Controle de frizz', 'performance'),
    ('Memória de Cachos', 'Memória de cachos', 'performance'),
    ('Cuidado com o Couro Cabeludo', 'Cuidado com o couro cabeludo', 'performance'),
    ('Uso Diário', 'Adequado para uso diário', 'marketing'),
    ('Tamanho Viagem', 'Tamanho viagem', 'marketing'),
    ('Uso Profissional', 'Uso profissional', 'marketing')
ON CONFLICT (name) DO NOTHING;

INSERT INTO scoring_models (name, version, description, is_active) VALUES
    ('Recomendação Geral', '1.0.0', 'Modelo base de recomendação para qualquer usuário/produto', TRUE),
    ('Pele Sensível', '1.0.0', 'Modelo ajustado para usuários com pele sensível', FALSE),
    ('Pele Seca', '1.0.0', 'Modelo ajustado para usuários com pele seca', FALSE),
    ('Pele Oleosa', '1.0.0', 'Modelo ajustado para usuários com pele oleosa', FALSE),
    ('Acne', '1.0.0', 'Modelo ajustado para usuários com acne', FALSE),
    ('Rosácea', '1.0.0', 'Modelo ajustado para usuários com rosácea', FALSE),
    ('Seguro na Gravidez', '1.0.0', 'Modelo ajustado para gestação e amamentação', FALSE),
    ('Cuidados Capilares', '1.0.0', 'Modelo geral para produtos capilares', FALSE),
    ('Cabelos Cacheados', '1.0.0', 'Modelo ajustado para cabelos cacheados', FALSE),
    ('Cabelos Lisos', '1.0.0', 'Modelo ajustado para cabelos lisos', FALSE),
    ('Cabelos Coloridos', '1.0.0', 'Modelo ajustado para cabelos coloridos ou quimicamente tratados', FALSE),
    ('Infantil', '1.0.0', 'Modelo ajustado para público infantil', FALSE),
    ('Pele Madura', '1.0.0', 'Modelo ajustado para pele madura', FALSE),
    ('Ecológico', '1.0.0', 'Modelo com foco em sustentabilidade e impacto ambiental', FALSE),
    ('Transparência de Ingredientes', '1.0.0', 'Modelo com foco em transparência da fórmula', FALSE),
    ('Confiança Científica', '1.0.0', 'Modelo com foco no nível de evidência científica', FALSE),
    ('Cuidados com o Couro Cabeludo', '1.0.0', 'Modelo focado em necessidades do couro cabeludo', FALSE),
    ('Couro Cabeludo Seco', '1.0.0', 'Modelo ajustado para couro cabeludo seco', FALSE),
    ('Couro Cabeludo Oleoso', '1.0.0', 'Modelo ajustado para couro cabeludo oleoso', FALSE),
    ('Cuidados com Barba', '1.0.0', 'Modelo ajustado para produtos de barba', FALSE),
    ('Maquiagem', '1.0.0', 'Modelo ajustado para produtos de maquiagem', FALSE),
    ('Maquiagem Alta Cobertura', '1.0.0', 'Modelo ajustado para maquiagem de alta cobertura', FALSE),
    ('Maquiagem Leve', '1.0.0', 'Modelo ajustado para maquiagem de cobertura leve', FALSE),
    ('Cuidado Infantil', '1.0.0', 'Modelo ajustado para produtos infantis', FALSE),
    ('Olhos Sensíveis', '1.0.0', 'Modelo ajustado para área dos olhos sensíveis', FALSE),
    ('Acne Intensiva', '1.0.0', 'Modelo ajustado para manejo intensivo de acne', FALSE),
    ('Hiperpigmentação', '1.0.0', 'Modelo ajustado para hiperpigmentação', FALSE),
    ('Melasma', '1.0.0', 'Modelo ajustado para melasma', FALSE),
    ('Psoríase', '1.0.0', 'Modelo ajustado para psoríase', FALSE),
    ('Pele Adolescente', '1.0.0', 'Modelo ajustado para pele adolescente', FALSE),
    ('Cosméticos Premium', '1.0.0', 'Modelo ajustado para posicionamento premium', FALSE)
ON CONFLICT (name, version) DO NOTHING;
